name: Deploy Testing Airflow DAGs

on:
  push:
    branches: [ testing ]
    paths:
      - 'dags/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: testing

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts || true

          # Debugging: Check if SSH key is properly created
          echo "Checking SSH key files..."
          ls -lah ~/.ssh
          echo "First 5 lines of id_rsa:"
          head -n 5 ~/.ssh/id_rsa || echo "Failed to read id_rsa"

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -v ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "echo 'SSH Connection Successful'"

      - name: Deploy DAGs to EC2
        run: |
          rsync -avz --delete ./dags/ ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:${{ secrets.DOCKER_COMPOSE_PATH }}/dags/

      - name: Restart Airflow Scheduler
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cd ${{ secrets.DOCKER_COMPOSE_PATH }} && docker-compose restart airflow-docker-airflow-scheduler-1"
