name: Deploy Airflow DAGs
on:
  push:
    branches:
      - testing
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: testing
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsd
          chmod 600 ~/.ssh/id_rsd
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy DAGs to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            cd /home/ec2-user
            if [ -d "airflow-dags" ]; then
              cd airflow-dags && git pull origin testing
            else
              git clone -b testing git@github.com:${{ github.repository }}.git airflow-dags
              cd airflow-dags
            fi
            cp -r dags/* /home/ec2-user/airflow-docker/dags/
            sudo docker restart airflow-docker-airflow-scheduler-1
          EOF
