name: Deploy Testing Airflow DAGs

on:
  push:
    branches: [ testing ]
    paths:
      - 'dags/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: testing
      
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      
      - name: Deploy DAGs to EC2
        run: |
          rsync -avz --delete ./dags/ ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:${{ secrets.DOCKER_COMPOSE_PATH }}/dags/
      
      - name: Restart Airflow (if needed)
        run: |
          ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cd ${{ secrets.DOCKER_COMPOSE_PATH }} && docker-compose restart airflow-docker-airflow-scheduler-1"
